---
- name: System Upgrade
  hosts: all
  serial: 1
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
    - name: Upgrade the OS
      apt:
        upgrade: dist
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: Check if reboot is required
        stat:
          path: /var/run/reboot-required
        register: reboot_required_result
    - name: Reboot
      reboot:
      when: reboot_required_result.stat.exists
...

